version: '3'
services:
    mysql:
        image: 'mysql/mysql-server'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'db_task'
            MYSQL_USER: 'codingdojo'
            MYSQL_PASSWORD: 'codingdojo'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p codingdojo"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8081:80
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_PORT: '3306'
        networks:
            - sail
        depends_on:
            - mysql
    project:
        restart: 'unless-stopped'
        build: final_exam/
        ports:
            - 8080:8080
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
