name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host:  ${{ secrets.EC2_HOST }} # Replace with your EC2 instance's public IP address
        username:  ${{ secrets.EC2_USERNAME }} # Replace with your EC2 instance's SSH username
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          mkdir deploy && cd deploy && git clone git@github.com:jhusseth1/deploy-crud-app.git
       

    - name: SSH into EC2 instance and deploy containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # Replace with your EC2 instance's public IP address
        username: ${{ secrets.EC2_USERNAME }} # Replace with your EC2 instance's SSH username
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd deploy && docker-compose up --build -d
